
<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>

<form action="<?= $variables['purchasing']['formAction']  ?>" method="get">
    <input type="hidden" name="sum" value="<?= $variables['purchasing']['sum'] ?>"/>
    <input type="hidden" name="account" value="<?= $variables['purchasing']['account'] ?>"/>
    <input type="hidden" name="desc" value="<?= $variables['purchasing']['desc'] ?>"/>
    <input type="hidden" name="signature" value="<?= $variables['purchasing']['signature'] ?>"/>
    <? if ($variables['purchasing']['email']):?>
        <input type="hidden" name="customerEmail" value="<?= $variables['purchasing']['email'] ?>"/>
    <?endif;?>
    <? if ($variables['purchasing']['phone']):?>
        <input type="hidden" name="customerPhone" value="<?= $variables['purchasing']['phone'] ?>"/>
    <?endif;?>
    <? if ($variables['purchasing']['items']):?>
        <input type="hidden" name="cashItems" value="<?= $variables['purchasing']['items'] ?>"/>
    <?endif;?>
    <div>
        <?= $this->translate('payment_redirect_text') ?> Unitpay.
    </div>

    <div>
        <input type="submit" value="<?= $this->translate('pay') ?>" class="button big"/>
    </div>
</form>